#! /bin/bash
#
# bootstrap
#
# Bootstrap file to use when setting up user account.
# This script is meant to be idempotent.
#



#====================================================================
# Script Setup

echo
echo 'Running user account bootstrap process...'

TDIR="$HOME/code/dotlib"
OSNAME="$(uname -s)"

# not actually necessary as everything refers to absolute paths
cd "$HOME" || { echo 'ERROR Cannot cd into ~'; exit 1; }




#====================================================================
# Create Directory Structure

# code/
mkdir -p "$HOME/code/bin"
mkdir -p "$HOME/code/config"
mkdir -p "$HOME/code/env"
mkdir -p "$HOME/code/managed"
mkdir -p "$HOME/code/scratch"


#====================================================================
# Copy Templates

## dotenv_local (~/.dotenv_local)
if [[ -f "$HOME/dotenv_local" ]]; then
  echo "WARNING: '$HOME/dotenv_local' already exists. Skipping."

else
  cp "$TDIR/dotenv_local" "$HOME/.dotenv_local"
  chmod 600 "$HOME/.dotenv_local"
fi


## git user (~/.config/git/user)
if [[ -f "$HOME/.config/git/user" ]]; then
  echo "WARNING: '$HOME/.config/git/user' already exists. Skipping."

else
  echo "Please enter email address for use with git:"
  read -r GIT_EMAIL
  sed "s/email@example.com/$GIT_EMAIL/g" "$TDIR/git_user_template" > "$HOME/.config/git/user"
fi


## .ssh/config ($HOME/.ssh)
# note ssh doesn't allow this file to be symlinked
# TODO: switch to yadm's templates
if [[ -f "$HOME/.ssh/config" ]]; then
  echo "WARNING: '$HOME/.ssh/config' already exists. Skipping."

else
  if [[ $OSNAME == "Darwin" ]]; then
    # macOS
    grep -v '# linux only' "$TDIR/ssh_config" > ~/.ssh/config

  else
    # linux
    grep -v '# macOS only' "$TDIR/ssh_config" > ~/.ssh/config
  fi

  chown "$USER:$USER" ~/.ssh/config
  chmod 600 ~/.ssh/config
fi


## bash_dessions_disable (~/.bash_sessions_disable)
if [[ $OSNAME == "Darwin" ]] && [[ ! -f "$HOME/.bash_sessions_disable" ]]; then
  cp "$TDIR/bash_sessions_disable" "$HOME/.bash_sessions_disable"
fi


#====================================================================
# Initialize Executables 

# Note: zsh plugin manager (zinit) will bootstrap itself when zsh is used
# Note: tmux plugin manager (tpm) will bootstrap itself tmux is used

# fzf
if [[ ! -f "$HOME/.fzf.bash" ]]; then
  if [[ -f '/usr/local/opt/fzf/install' ]]; then
    '/usr/local/opt/fzf/install'
  elif [[ -f "$HOME/.fzf/install" ]]; then
    "$HOME/.fzf/install"
  else
    echo "WARNING: fzf install command not found. Skipping installation."
    echo 'Run ~/.fzf/install when ready'
  fi
else
  echo "WARNING: fzf has already been initialized. Skipping."
fi


# vim Plug plugin manager
if [[ -x "$(command -v nvim)" ]]; then
  nvim '+PlugUpdate' '+PlugClean!' '+qall'
elif [[ -x "$(command -v vim)" ]]; then
  vim '+PlugUpdate' '+PlugClean!' '+qall'
else
  echo "WARNING: vim or neovim were not found. Skipping plugin initialization."
fi


#====================================================================
# Final Instructions

echo "
Bootstrap complete! Please see README for final tasks.
"
